# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af53deeb097dd4d10e8315cf52bc8ed8046a9470395e7d0f046ae4c43ac28569384d5fe1624f0197e3341f42665b5d81e2c8cde10864c1b69fc16f12360b4a18

test:
  secret_key_base: df54aa8959cf5b4b14ba3e0ad97b103e67fb4d067fc1032fc7a700b42c399112963c15de5c1e660add3a01e5d72d521e0cc8195b1a5675b1f019fc2c7a232b8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
